### ISSUE TITLE
Feature request : Is it possible to change the background color?

### ISSUE THREAD

**Issue by pardub** [aiFdn/SN-JetBrains-Mono#1]
Hi,
Everything is in the title :)
Is it possible to modify the background color?

**Comment by SHSharkar** [comment]
Hello @pardub , and thanks for your message.

The theme file is a static CSS file that can contain a single value to set.

I have not applied any background or foreground color sets for this font style and kept the Standard Notes default theme color.

I will have to fork and apply custom theme colors if needed.
